apiVersion: v1
kind: Service
metadata:
  name: redis-master-gary
  labels:
    app: redis-gary
    role: master
    tier: backend
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: redis-gary
    role: master
    tier: backend
